spring.application.name=back-end

# Spring MVC Time
spring.mvc.async.request-timeout=600000

# Tomcat Time
server.tomcat.connection-timeout=600000
server.port=8080

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# Local dev endpoints
frontend.url=http://localhost:3000

algorithm.url=http://localhost:8000
